name: freelance_pi_mobile
description: Final Freelance Pi mobile client
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  socket_io_client: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
